DROP TABLE IF EXISTS STAFF;
CREATE TABLE STAFF
( STAFF_ID NUMBER NOT NULL UNIQUE PRIMARY KEY,
  FIRST_NAME VARCHAR2(250),
  LAST_NAME VARCHAR2(250),
  IDENTITY_NO VARCHAR2(250),
  AGE NUMBER,
  DATE_REQUESTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DATE_LAST_MODIFIED TIMESTAMP,
  MODIFICATION_COUNT NUMBER DEFAULT 0
);
DROP TABLE IF EXISTS STAFF_JOB;
CREATE TABLE STAFF_JOB
(   JOP_KEY NUMBER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    STAFF_ID NUMBER NOT NULL UNIQUE,
    JOB_NAME VARCHAR2(250),
    JOB_DEPARTMENT VARCHAR2(250),
    JOB_LEVEL VARCHAR2(250),
    TEAM_NAME VARCHAR2(250),
    MANAGER_NO NUMBER,
    DATE_REQUESTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATE_LAST_MODIFIED TIMESTAMP,
    MODIFICATION_COUNT NUMBER DEFAULT 0
);
DROP TABLE IF EXISTS STAFF_EMAIL;
CREATE TABLE STAFF_EMAIL
(   EMAIL_KEY NUMBER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    STAFF_ID NUMBER NOT NULL,
    EMAIL VARCHAR2(250),
    EMAIL_ACTIVE VARCHAR2(1),
    DATE_REQUESTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATE_LAST_MODIFIED TIMESTAMP,
    MODIFICATION_COUNT NUMBER DEFAULT 0
);
DROP TABLE IF EXISTS STAFF_LOCATION;
CREATE TABLE STAFF_LOCATION
(   LOCATION_KEY NUMBER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    STAFF_ID NUMBER NOT NULL UNIQUE,
    CITY VARCHAR2(250),
    PROVINCE VARCHAR2(250),
    COUNTRY VARCHAR2(250),
    DATE_REQUESTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATE_LAST_MODIFIED TIMESTAMP,
    MODIFICATION_COUNT NUMBER DEFAULT 0
);
